title: Karl DeVries
linkedin_username: karl-devries-a1480864
github_username:  karl-devries
permalink: :title
repository: "karl-devries/karl-devries.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-minimal
include:
  - README.md
